%Base on QC function GoNoGo_Phase     
function [trialsNames,trialsMatrix] = carouselTaskTrialPhase(S,PhaseName)
    switch(PhaseName)
        case 'simpleCarousel'
            trialsNames = {'ICR_1','PWD/J_1','C57BL/6_1','ICRovx_1','BALBC_1','EMPTY_1'...
                'ICR_2','PWD/J_2','C57BL/6_2','ICRovx_2','BALBC_1','EMPTY_2'};
            trialsMatrix=[...
            %  1.type, 2.proba, 3.sound, 4.LickTimer,       5.LickValve, 6.NaN  7. marker       8.noLickTimer     9.noLickValve
            
            1,      0.0833,          1,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.Reward,         S.GUI.RewardValve;...   
            2,      0.0833,          2,    S.Reward,         S.GUI.RewardValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...
            3,      0.0833,          3,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.Reward,         S.GUI.RewardValve;...
            4,      0.0833,          4,    S.Reward,         S.GUI.RewardValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...
            5,      0.0833,          5,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.Reward,         S.GUI.RewardValve;...
            6,      0.0833,          6,    S.Reward,         S.GUI.RewardValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...
            7,      0.0833,          7,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.Reward,         S.GUI.RewardValve;...
            8,      0.0833,          8,    S.Reward,         S.GUI.RewardValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...
            9,      0.0833,          9,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.Reward,         S.GUI.RewardValve;...
            10,      0.0833,          10,    S.Reward,         S.GUI.RewardValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...
            11,      0.0833,          11,    S.Reward,         S.GUI.RewardValve, NaN,  double('o'),    S.Reward,         S.GUI.RewardValve;...
            12,      0.0833,          12,    S.Reward,         S.GUI.RewardValve, NaN,  double('v'),    S.Reward,         S.GUI.RewardValve;...
            ];
        
    end
end

